"""Add billing_schedule_line_items table and update billing_schedules schema

Revision ID: b382e5c4a4a8
Revises: ffd63964a535
Create Date: 2026-04-11 13:02:54.973135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b382e5c4a4a8'
down_revision: Union[str, None] = 'ffd63964a535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('billing_schedules_ibfk_2', 'billing_schedules', type_='foreignkey')
    op.drop_column('billing_schedules', 'description')
    op.drop_column('billing_schedules', 'service_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_schedules', sa.Column('service_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('billing_schedules', sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.create_foreign_key('billing_schedules_ibfk_2', 'billing_schedules', 'service_catalog', ['service_id'], ['id'])
    # ### end Alembic commands ###
